name: Generate-Android-and-iOS-Artifacts

on: [push]

jobs:
  Generate-Android-and-iOS-Artifacts:
    name: Generate Android and iOS Artifacts
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install Dependencies
        run: npm install
      - name: Install Expo CLI
        run: npm install -g expo-cli
      - name: Run expo prebuild to generate iOS and Android directories
        run: npx expo prebuild

      - name: Check if ios directory exists
        run: if [ -d "ios" ]; then echo "iOS directory exists"; else echo "iOS directory not found"; exit 1; fi
      - name: Check if Android directory exists
        run: if [ -d "android" ]; then echo "Android directory exists"; else echo "Android directory not found"; exit 1; fi
      - name: Upload iOS directory as artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ios-directory
          path: ios/
      - name: Upload Android directory as artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: android-directory
          path: android/
